// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: api/web/v1/web.proto

package web

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PluginsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PluginsRequest) Reset() {
	*x = PluginsRequest{}
	mi := &file_api_web_v1_web_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginsRequest) ProtoMessage() {}

func (x *PluginsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_web_v1_web_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginsRequest.ProtoReflect.Descriptor instead.
func (*PluginsRequest) Descriptor() ([]byte, []int) {
	return file_api_web_v1_web_proto_rawDescGZIP(), []int{0}
}

type PluginsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PluginNames   []string               `protobuf:"bytes,1,rep,name=plugin_names,json=pluginNames,proto3" json:"plugin_names,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PluginsResponse) Reset() {
	*x = PluginsResponse{}
	mi := &file_api_web_v1_web_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginsResponse) ProtoMessage() {}

func (x *PluginsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_web_v1_web_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginsResponse.ProtoReflect.Descriptor instead.
func (*PluginsResponse) Descriptor() ([]byte, []int) {
	return file_api_web_v1_web_proto_rawDescGZIP(), []int{1}
}

func (x *PluginsResponse) GetPluginNames() []string {
	if x != nil {
		return x.PluginNames
	}
	return nil
}

var File_api_web_v1_web_proto protoreflect.FileDescriptor

const file_api_web_v1_web_proto_rawDesc = "" +
	"\n" +
	"\x14api/web/v1/web.proto\x12\n" +
	"api.web.v1\"\x10\n" +
	"\x0ePluginsRequest\"4\n" +
	"\x0fPluginsResponse\x12!\n" +
	"\fplugin_names\x18\x01 \x03(\tR\vpluginNames2P\n" +
	"\n" +
	"ServiceAPI\x12B\n" +
	"\aPlugins\x12\x1a.api.web.v1.PluginsRequest\x1a\x1b.api.web.v1.PluginsResponseB.Z,github.com/easyp-tech/service/api/web/v1;webb\x06proto3"

var (
	file_api_web_v1_web_proto_rawDescOnce sync.Once
	file_api_web_v1_web_proto_rawDescData []byte
)

func file_api_web_v1_web_proto_rawDescGZIP() []byte {
	file_api_web_v1_web_proto_rawDescOnce.Do(func() {
		file_api_web_v1_web_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_web_v1_web_proto_rawDesc), len(file_api_web_v1_web_proto_rawDesc)))
	})
	return file_api_web_v1_web_proto_rawDescData
}

var file_api_web_v1_web_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_web_v1_web_proto_goTypes = []any{
	(*PluginsRequest)(nil),  // 0: api.web.v1.PluginsRequest
	(*PluginsResponse)(nil), // 1: api.web.v1.PluginsResponse
}
var file_api_web_v1_web_proto_depIdxs = []int32{
	0, // 0: api.web.v1.ServiceAPI.Plugins:input_type -> api.web.v1.PluginsRequest
	1, // 1: api.web.v1.ServiceAPI.Plugins:output_type -> api.web.v1.PluginsResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_web_v1_web_proto_init() }
func file_api_web_v1_web_proto_init() {
	if File_api_web_v1_web_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_web_v1_web_proto_rawDesc), len(file_api_web_v1_web_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_web_v1_web_proto_goTypes,
		DependencyIndexes: file_api_web_v1_web_proto_depIdxs,
		MessageInfos:      file_api_web_v1_web_proto_msgTypes,
	}.Build()
	File_api_web_v1_web_proto = out.File
	file_api_web_v1_web_proto_goTypes = nil
	file_api_web_v1_web_proto_depIdxs = nil
}
