versions:
- v0.1.9
- v0.1.8
- v0.1.7
- v0.1.6
- v0.1.5
- v0.1.10
- version: v0.1.4
  dockerfile: Dockerfile.github
- version: v0.1.2
  dockerfile: Dockerfile.source
- version: v0.1.1
  dockerfile: Dockerfile.source
