// Code generated by "stringer -type=CockroachSSL -linecomment"; DO NOT EDIT.

package connectors

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[CockroachSSLDisable-1]
	_ = x[CockroachSSLAllow-2]
	_ = x[CockroachSSLPrefer-3]
	_ = x[CockroachSSLRequire-4]
	_ = x[CockroachSSLVerifyCa-5]
	_ = x[CockroachSSLVerifyFull-6]
}

const _CockroachSSL_name = "disableallowpreferrequireverify-caverify-full"

var _CockroachSSL_index = [...]uint8{0, 7, 12, 18, 25, 34, 45}

func (i CockroachSSL) String() string {
	i -= 1
	if i >= CockroachSSL(len(_CockroachSSL_index)-1) {
		return "CockroachSSL(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _CockroachSSL_name[_CockroachSSL_index[i]:_CockroachSSL_index[i+1]]
}
