// Code generated by "stringer -type=PostgresSSL -linecomment"; DO NOT EDIT.

package connectors

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[PostgresSSLDisable-1]
	_ = x[PostgresSSLAllow-2]
	_ = x[PostgresSSLPrefer-3]
	_ = x[PostgresSSLRequire-4]
	_ = x[PostgresSSLVerifyCa-5]
	_ = x[PostgresSSLVerifyFull-6]
}

const _PostgresSSL_name = "disableallowpreferrequireverify-caverify-full"

var _PostgresSSL_index = [...]uint8{0, 7, 12, 18, 25, 34, 45}

func (i PostgresSSL) String() string {
	i -= 1
	if i >= PostgresSSL(len(_PostgresSSL_index)-1) {
		return "PostgresSSL(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _PostgresSSL_name[_PostgresSSL_index[i]:_PostgresSSL_index[i+1]]
}
