// Code generated by "stringer -type=Command -linecomment"; DO NOT EDIT.

package migrations

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Up-1]
	_ = x[Down-2]
}

const _Command_name = "updown"

var _Command_index = [...]uint8{0, 2, 6}

func (i Command) String() string {
	i -= 1
	if i >= Command(len(_Command_index)-1) {
		return "Command(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _Command_name[_Command_index[i]:_Command_index[i+1]]
}
