package main

import (
	"fmt"
	"io"
	"os"
	"os/exec"
	"strconv"
	"time"

	"google.golang.org/protobuf/proto"
	"google.golang.org/protobuf/types/pluginpb"
)

func main() {
	// 1. Handle MOCK_SLEEP
	if sleepStr := os.Getenv("MOCK_SLEEP"); sleepStr != "" {
		if d, err := time.ParseDuration(sleepStr); err == nil {
			time.Sleep(d)
		}
	}

	// 2. Handle MOCK_FORK
	if os.Getenv("MOCK_FORK") == "1" {
		// Fork a child process that sleeps
		cmd := exec.Command(os.Args[0])
		cmd.Env = append(os.Environ(), "MOCK_SLEEP=1h", "MOCK_FORK=0")
		if err := cmd.Start(); err != nil {
			fmt.Fprintf(os.Stderr, "failed to fork: %v\n", err)
		}
		// Give it a tiny bit of time to start
		time.Sleep(10 * time.Millisecond)
	}

	// 3. Handle MOCK_STDERR
	if stderrText := os.Getenv("MOCK_STDERR"); stderrText != "" {
		fmt.Fprint(os.Stderr, stderrText)
	}

	// 4. Handle MOCK_PRINT_ENV
	if os.Getenv("MOCK_PRINT_ENV") == "1" {
		for _, e := range os.Environ() {
			fmt.Fprintln(os.Stderr, e)
		}
	}

	// 5. Handle MOCK_EXIT_CODE
	if exitCodeStr := os.Getenv("MOCK_EXIT_CODE"); exitCodeStr != "" {
		if code, err := strconv.Atoi(exitCodeStr); err == nil && code != 0 {
			os.Exit(code)
		}
	}

	// 6. Handle MOCK_OUTPUT_SIZE (write N bytes to stdout instead of proto response)
	if outSizeStr := os.Getenv("MOCK_OUTPUT_SIZE"); outSizeStr != "" {
		if size, err := strconv.ParseInt(outSizeStr, 10, 64); err == nil {
			// Write size bytes of junk
			buf := make([]byte, 1024)
			for i := range buf {
				buf[i] = 'A'
			}
			var written int64
			for written < size {
				toWrite := size - written
				if toWrite > int64(len(buf)) {
					toWrite = int64(len(buf))
				}
				n, _ := os.Stdout.Write(buf[:toWrite])
				if n <= 0 {
					break
				}
				written += int64(n)
			}
			return
		}
	}

	// Default behavior: Read CodeGeneratorRequest from stdin and write a valid CodeGeneratorResponse
	input, err := io.ReadAll(os.Stdin)
	if err != nil {
		fmt.Fprintf(os.Stderr, "failed to read stdin: %v\n", err)
		os.Exit(1)
	}

	var req pluginpb.CodeGeneratorRequest
	if err := proto.Unmarshal(input, &req); err != nil {
		fmt.Fprintf(os.Stderr, "failed to unmarshal request: %v\n", err)
		os.Exit(1)
	}

	resp := &pluginpb.CodeGeneratorResponse{
		SupportedFeatures: proto.Uint64(uint64(pluginpb.CodeGeneratorResponse_FEATURE_PROTO3_OPTIONAL)),
		File: []*pluginpb.CodeGeneratorResponse_File{
			{
				Name:    proto.String("generated.go"),
				Content: proto.String("// Code generated by mock plugin. DO NOT EDIT.\npackage generated\n"),
			},
		},
	}

	out, err := proto.Marshal(resp)
	if err != nil {
		fmt.Fprintf(os.Stderr, "failed to marshal response: %v\n", err)
		os.Exit(1)
	}

	if _, err := os.Stdout.Write(out); err != nil {
		fmt.Fprintf(os.Stderr, "failed to write response: %v\n", err)
		os.Exit(1)
	}
}
