// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        (unknown)
// source: api/generator/v1/generator.proto

package generator

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	pluginpb "google.golang.org/protobuf/types/pluginpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GenerateCodeRequest is the request message for the GenerateCode RPC.
type GenerateCodeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// code_generator_request is the standard protobuf code generator request.
	CodeGeneratorRequest *pluginpb.CodeGeneratorRequest `protobuf:"bytes,1,opt,name=code_generator_request,json=codeGeneratorRequest,proto3" json:"code_generator_request,omitempty"`
	// plugin_name is the name of the plugin to use for generation.
	PluginName    string `protobuf:"bytes,2,opt,name=plugin_name,json=pluginName,proto3" json:"plugin_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateCodeRequest) Reset() {
	*x = GenerateCodeRequest{}
	mi := &file_api_generator_v1_generator_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateCodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateCodeRequest) ProtoMessage() {}

func (x *GenerateCodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_generator_v1_generator_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateCodeRequest.ProtoReflect.Descriptor instead.
func (*GenerateCodeRequest) Descriptor() ([]byte, []int) {
	return file_api_generator_v1_generator_proto_rawDescGZIP(), []int{0}
}

func (x *GenerateCodeRequest) GetCodeGeneratorRequest() *pluginpb.CodeGeneratorRequest {
	if x != nil {
		return x.CodeGeneratorRequest
	}
	return nil
}

func (x *GenerateCodeRequest) GetPluginName() string {
	if x != nil {
		return x.PluginName
	}
	return ""
}

// GenerateCodeResponse is the response message for the GenerateCode RPC.
type GenerateCodeResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// code_generator_response is the standard protobuf code generator response.
	CodeGeneratorResponse *pluginpb.CodeGeneratorResponse `protobuf:"bytes,1,opt,name=code_generator_response,json=codeGeneratorResponse,proto3" json:"code_generator_response,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *GenerateCodeResponse) Reset() {
	*x = GenerateCodeResponse{}
	mi := &file_api_generator_v1_generator_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateCodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateCodeResponse) ProtoMessage() {}

func (x *GenerateCodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_generator_v1_generator_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateCodeResponse.ProtoReflect.Descriptor instead.
func (*GenerateCodeResponse) Descriptor() ([]byte, []int) {
	return file_api_generator_v1_generator_proto_rawDescGZIP(), []int{1}
}

func (x *GenerateCodeResponse) GetCodeGeneratorResponse() *pluginpb.CodeGeneratorResponse {
	if x != nil {
		return x.CodeGeneratorResponse
	}
	return nil
}

// PluginsRequest is the request message for the Plugins RPC.
type PluginsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PluginsRequest) Reset() {
	*x = PluginsRequest{}
	mi := &file_api_generator_v1_generator_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginsRequest) ProtoMessage() {}

func (x *PluginsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_generator_v1_generator_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginsRequest.ProtoReflect.Descriptor instead.
func (*PluginsRequest) Descriptor() ([]byte, []int) {
	return file_api_generator_v1_generator_proto_rawDescGZIP(), []int{2}
}

// PluginsResponse is the response message for the Plugins RPC.
type PluginsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// plugins is the list of available plugins.
	Plugins       []*PluginInfo `protobuf:"bytes,1,rep,name=plugins,proto3" json:"plugins,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PluginsResponse) Reset() {
	*x = PluginsResponse{}
	mi := &file_api_generator_v1_generator_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginsResponse) ProtoMessage() {}

func (x *PluginsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_generator_v1_generator_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginsResponse.ProtoReflect.Descriptor instead.
func (*PluginsResponse) Descriptor() ([]byte, []int) {
	return file_api_generator_v1_generator_proto_rawDescGZIP(), []int{3}
}

func (x *PluginsResponse) GetPlugins() []*PluginInfo {
	if x != nil {
		return x.Plugins
	}
	return nil
}

// PluginInfo message represents information about a plugin.
type PluginInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// id is the unique identifier for the plugin.
	// Example: "123e4567-e89b-12d3-a456-426614174000"
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// group is the group to which the plugin belongs.
	// Example: "protocolbuffers"
	Group string `protobuf:"bytes,2,opt,name=group,proto3" json:"group,omitempty"`
	// name is the name of the plugin.
	// Example: "go"
	Name string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	// version is the version of the plugin.
	// Example: "v1.5.1"
	Version string `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	// created_at is the timestamp when the plugin was installed.
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PluginInfo) Reset() {
	*x = PluginInfo{}
	mi := &file_api_generator_v1_generator_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginInfo) ProtoMessage() {}

func (x *PluginInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_generator_v1_generator_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginInfo.ProtoReflect.Descriptor instead.
func (*PluginInfo) Descriptor() ([]byte, []int) {
	return file_api_generator_v1_generator_proto_rawDescGZIP(), []int{4}
}

func (x *PluginInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PluginInfo) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *PluginInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PluginInfo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *PluginInfo) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

var File_api_generator_v1_generator_proto protoreflect.FileDescriptor

const file_api_generator_v1_generator_proto_rawDesc = "" +
	"\n" +
	" api/generator/v1/generator.proto\x12\x10api.generator.v1\x1a%google/protobuf/compiler/plugin.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x9c\x01\n" +
	"\x13GenerateCodeRequest\x12d\n" +
	"\x16code_generator_request\x18\x01 \x01(\v2..google.protobuf.compiler.CodeGeneratorRequestR\x14codeGeneratorRequest\x12\x1f\n" +
	"\vplugin_name\x18\x02 \x01(\tR\n" +
	"pluginName\"\x7f\n" +
	"\x14GenerateCodeResponse\x12g\n" +
	"\x17code_generator_response\x18\x01 \x01(\v2/.google.protobuf.compiler.CodeGeneratorResponseR\x15codeGeneratorResponse\"\x10\n" +
	"\x0ePluginsRequest\"I\n" +
	"\x0fPluginsResponse\x126\n" +
	"\aplugins\x18\x01 \x03(\v2\x1c.api.generator.v1.PluginInfoR\aplugins\"\x9b\x01\n" +
	"\n" +
	"PluginInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05group\x18\x02 \x01(\tR\x05group\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x04 \x01(\tR\aversion\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt2\xbb\x01\n" +
	"\n" +
	"ServiceAPI\x12]\n" +
	"\fGenerateCode\x12%.api.generator.v1.GenerateCodeRequest\x1a&.api.generator.v1.GenerateCodeResponse\x12N\n" +
	"\aPlugins\x12 .api.generator.v1.PluginsRequest\x1a!.api.generator.v1.PluginsResponseB:Z8github.com/easyp-tech/service/api/generator/v1;generatorb\x06proto3"

var (
	file_api_generator_v1_generator_proto_rawDescOnce sync.Once
	file_api_generator_v1_generator_proto_rawDescData []byte
)

func file_api_generator_v1_generator_proto_rawDescGZIP() []byte {
	file_api_generator_v1_generator_proto_rawDescOnce.Do(func() {
		file_api_generator_v1_generator_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_generator_v1_generator_proto_rawDesc), len(file_api_generator_v1_generator_proto_rawDesc)))
	})
	return file_api_generator_v1_generator_proto_rawDescData
}

var file_api_generator_v1_generator_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_api_generator_v1_generator_proto_goTypes = []any{
	(*GenerateCodeRequest)(nil),            // 0: api.generator.v1.GenerateCodeRequest
	(*GenerateCodeResponse)(nil),           // 1: api.generator.v1.GenerateCodeResponse
	(*PluginsRequest)(nil),                 // 2: api.generator.v1.PluginsRequest
	(*PluginsResponse)(nil),                // 3: api.generator.v1.PluginsResponse
	(*PluginInfo)(nil),                     // 4: api.generator.v1.PluginInfo
	(*pluginpb.CodeGeneratorRequest)(nil),  // 5: google.protobuf.compiler.CodeGeneratorRequest
	(*pluginpb.CodeGeneratorResponse)(nil), // 6: google.protobuf.compiler.CodeGeneratorResponse
	(*timestamppb.Timestamp)(nil),          // 7: google.protobuf.Timestamp
}
var file_api_generator_v1_generator_proto_depIdxs = []int32{
	5, // 0: api.generator.v1.GenerateCodeRequest.code_generator_request:type_name -> google.protobuf.compiler.CodeGeneratorRequest
	6, // 1: api.generator.v1.GenerateCodeResponse.code_generator_response:type_name -> google.protobuf.compiler.CodeGeneratorResponse
	4, // 2: api.generator.v1.PluginsResponse.plugins:type_name -> api.generator.v1.PluginInfo
	7, // 3: api.generator.v1.PluginInfo.created_at:type_name -> google.protobuf.Timestamp
	0, // 4: api.generator.v1.ServiceAPI.GenerateCode:input_type -> api.generator.v1.GenerateCodeRequest
	2, // 5: api.generator.v1.ServiceAPI.Plugins:input_type -> api.generator.v1.PluginsRequest
	1, // 6: api.generator.v1.ServiceAPI.GenerateCode:output_type -> api.generator.v1.GenerateCodeResponse
	3, // 7: api.generator.v1.ServiceAPI.Plugins:output_type -> api.generator.v1.PluginsResponse
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_api_generator_v1_generator_proto_init() }
func file_api_generator_v1_generator_proto_init() {
	if File_api_generator_v1_generator_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_generator_v1_generator_proto_rawDesc), len(file_api_generator_v1_generator_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_generator_v1_generator_proto_goTypes,
		DependencyIndexes: file_api_generator_v1_generator_proto_depIdxs,
		MessageInfos:      file_api_generator_v1_generator_proto_msgTypes,
	}.Build()
	File_api_generator_v1_generator_proto = out.File
	file_api_generator_v1_generator_proto_goTypes = nil
	file_api_generator_v1_generator_proto_depIdxs = nil
}
