// Code generated by protoc-gen-mcp. DO NOT EDIT.
// source: api/generator/v1/generator.proto

package generator

import (
	context "context"
	errors "errors"
	mcpruntime "github.com/easyp-tech/protoc-gen-mcp/mcpruntime"
	mcp "github.com/modelcontextprotocol/go-sdk/mcp"
)

// ServiceAPIToolHandler defines the business logic required by generated MCP tools.
type ServiceAPIToolHandler interface {
	Plugins(ctx context.Context, req *PluginsRequest) (*PluginsResponse, error)
}

// RegisterServiceAPITools registers generated MCP tools for ServiceAPI.
func RegisterServiceAPITools(server *mcp.Server, impl ServiceAPIToolHandler, opts ...mcpruntime.RegisterOption) error {
	if impl == nil {
		return errors.New("RegisterServiceAPITools: impl is nil")
	}
	if err := mcpruntime.RegisterProtoTool(server, mcpruntime.ToolSpec[*PluginsRequest, *PluginsResponse]{
		Name:             "plugins_list",
		Title:            "List plugins",
		Description:      "List available plugins with optional filters: group, name, version, tags.",
		Namespace:        "",
		InputSchemaJSON:  ServiceAPI_Plugins_ToolSpecInputSchemaJSON,
		OutputSchemaJSON: ServiceAPI_Plugins_ToolSpecOutputSchemaJSON,
		Annotations:      nil,
		Icons:            nil,
		NewRequest:       func() *PluginsRequest { return &PluginsRequest{} },
		NewResponse:      func() *PluginsResponse { return &PluginsResponse{} },
		Handler:          impl.Plugins,
	}, opts...); err != nil {
		return err
	}
	return nil
}

const ServiceAPI_Plugins_ToolSpecInputSchemaJSON = "{\"type\":\"object\",\"properties\":{\"group\":{\"type\":[\"string\",\"null\"],\"examples\":[\"example\"]},\"name\":{\"type\":[\"string\",\"null\"],\"examples\":[\"example\"]},\"pageSize\":{\"type\":[\"integer\",\"null\"],\"examples\":[1]},\"pageToken\":{\"type\":[\"string\",\"null\"],\"examples\":[\"example\"]},\"tags\":{\"type\":[\"array\",\"null\"],\"items\":{\"type\":\"string\",\"examples\":[\"example\"]},\"examples\":[[\"example\"]]},\"version\":{\"type\":[\"string\",\"null\"],\"examples\":[\"example\"]}},\"examples\":[{\"group\":\"example\",\"name\":\"example\",\"pageSize\":1,\"pageToken\":\"example\",\"tags\":[\"example\"],\"version\":\"example\"}],\"additionalProperties\":false}"

const ServiceAPI_Plugins_ToolSpecOutputSchemaJSON = "{\"type\":\"object\",\"properties\":{\"nextPageToken\":{\"type\":\"string\",\"examples\":[\"example\"]},\"plugins\":{\"type\":[\"array\",\"null\"],\"items\":{\"type\":\"object\",\"properties\":{\"created_at\":{\"type\":\"string\",\"examples\":[\"2026-03-09T10:11:12Z\"],\"format\":\"date-time\"},\"group\":{\"type\":\"string\",\"examples\":[\"example\"]},\"id\":{\"type\":\"string\",\"examples\":[\"example\"]},\"name\":{\"type\":\"string\",\"examples\":[\"example\"]},\"tags\":{\"type\":[\"array\",\"null\"],\"items\":{\"type\":\"string\",\"examples\":[\"example\"]},\"examples\":[[\"example\"]]},\"version\":{\"type\":\"string\",\"examples\":[\"example\"]}},\"examples\":[{\"created_at\":\"2026-03-09T10:11:12Z\",\"group\":\"example\",\"id\":\"example\",\"name\":\"example\",\"tags\":[\"example\"],\"version\":\"example\"}],\"required\":[\"id\",\"group\",\"name\",\"version\",\"created_at\"],\"additionalProperties\":false},\"examples\":[[{\"created_at\":\"2026-03-09T10:11:12Z\",\"group\":\"example\",\"id\":\"example\",\"name\":\"example\",\"tags\":[\"example\"],\"version\":\"example\"}]]},\"total\":{\"type\":\"integer\",\"examples\":[-1]}},\"examples\":[{\"nextPageToken\":\"example\",\"plugins\":[{\"created_at\":\"2026-03-09T10:11:12Z\",\"group\":\"example\",\"id\":\"example\",\"name\":\"example\",\"tags\":[\"example\"],\"version\":\"example\"}],\"total\":-1}],\"required\":[\"total\",\"nextPageToken\"],\"additionalProperties\":false}"
