// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v0.14.1-v0.16.1-bufbuild-protocompile-easyp-modified
// source: api/generator/v1/generator.proto

package generator

import (
	_ "github.com/easyp-tech/protoc-gen-easydoc/doc/v1"
	_ "github.com/easyp-tech/protoc-gen-mcp/mcp/options/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	pluginpb "google.golang.org/protobuf/types/pluginpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request message for code generation.
type GenerateCodeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Standard protobuf code generator request.
	//
	// This should contain the proto files to process and any plugin-specific parameters.
	// The request is passed directly to the plugin's stdin.
	CodeGeneratorRequest *pluginpb.CodeGeneratorRequest `protobuf:"bytes,1,opt,name=code_generator_request,json=codeGeneratorRequest,proto3" json:"code_generator_request,omitempty"`
	// Name of the plugin to use for generation.
	//
	// Format: `<group>/<name>:<version>`
	//
	// Examples:
	// - `protocolbuffers/go:v1.36.10`
	// - `grpc/go:v1.5.1`
	// - `grpc-ecosystem/gateway:latest`
	PluginName    string `protobuf:"bytes,2,opt,name=plugin_name,json=pluginName,proto3" json:"plugin_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateCodeRequest) Reset() {
	*x = GenerateCodeRequest{}
	mi := &file_api_generator_v1_generator_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateCodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateCodeRequest) ProtoMessage() {}

func (x *GenerateCodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_generator_v1_generator_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateCodeRequest.ProtoReflect.Descriptor instead.
func (*GenerateCodeRequest) Descriptor() ([]byte, []int) {
	return file_api_generator_v1_generator_proto_rawDescGZIP(), []int{0}
}

func (x *GenerateCodeRequest) GetCodeGeneratorRequest() *pluginpb.CodeGeneratorRequest {
	if x != nil {
		return x.CodeGeneratorRequest
	}
	return nil
}

func (x *GenerateCodeRequest) GetPluginName() string {
	if x != nil {
		return x.PluginName
	}
	return ""
}

// Response message for code generation.
type GenerateCodeResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Standard protobuf code generator response.
	//
	// Contains the generated files and any error messages from the plugin.
	// Check the `error` field in the response for plugin-level errors.
	CodeGeneratorResponse *pluginpb.CodeGeneratorResponse `protobuf:"bytes,1,opt,name=code_generator_response,json=codeGeneratorResponse,proto3" json:"code_generator_response,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *GenerateCodeResponse) Reset() {
	*x = GenerateCodeResponse{}
	mi := &file_api_generator_v1_generator_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateCodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateCodeResponse) ProtoMessage() {}

func (x *GenerateCodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_generator_v1_generator_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateCodeResponse.ProtoReflect.Descriptor instead.
func (*GenerateCodeResponse) Descriptor() ([]byte, []int) {
	return file_api_generator_v1_generator_proto_rawDescGZIP(), []int{1}
}

func (x *GenerateCodeResponse) GetCodeGeneratorResponse() *pluginpb.CodeGeneratorResponse {
	if x != nil {
		return x.CodeGeneratorResponse
	}
	return nil
}

// Request message for listing plugins.
type PluginsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Filter by exact plugin group.
	//
	// Omit to return plugins from all groups.
	Group *string `protobuf:"bytes,1,opt,name=group,proto3,oneof" json:"group,omitempty"`
	// Filter by exact plugin name.
	//
	// Omit to return plugins with any name.
	Name *string `protobuf:"bytes,2,opt,name=name,proto3,oneof" json:"name,omitempty"`
	// Filter by exact plugin version.
	//
	// Omit to return all versions.
	Version *string `protobuf:"bytes,3,opt,name=version,proto3,oneof" json:"version,omitempty"`
	// Filter by tags.
	//
	// A plugin must contain all specified tags to match.
	Tags          []string `protobuf:"bytes,4,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PluginsRequest) Reset() {
	*x = PluginsRequest{}
	mi := &file_api_generator_v1_generator_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginsRequest) ProtoMessage() {}

func (x *PluginsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_generator_v1_generator_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginsRequest.ProtoReflect.Descriptor instead.
func (*PluginsRequest) Descriptor() ([]byte, []int) {
	return file_api_generator_v1_generator_proto_rawDescGZIP(), []int{2}
}

func (x *PluginsRequest) GetGroup() string {
	if x != nil && x.Group != nil {
		return *x.Group
	}
	return ""
}

func (x *PluginsRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *PluginsRequest) GetVersion() string {
	if x != nil && x.Version != nil {
		return *x.Version
	}
	return ""
}

func (x *PluginsRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

// Response message for listing plugins.
type PluginsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// List of available plugins matching the supplied filters.
	//
	// Plugins are sorted by group, name, and version.
	Plugins []*PluginInfo `protobuf:"bytes,1,rep,name=plugins,proto3" json:"plugins,omitempty"`
	// Number of matching plugins in this response.
	Total         int32 `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PluginsResponse) Reset() {
	*x = PluginsResponse{}
	mi := &file_api_generator_v1_generator_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginsResponse) ProtoMessage() {}

func (x *PluginsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_generator_v1_generator_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginsResponse.ProtoReflect.Descriptor instead.
func (*PluginsResponse) Descriptor() ([]byte, []int) {
	return file_api_generator_v1_generator_proto_rawDescGZIP(), []int{3}
}

func (x *PluginsResponse) GetPlugins() []*PluginInfo {
	if x != nil {
		return x.Plugins
	}
	return nil
}

func (x *PluginsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

// Information about a registered plugin.
type PluginInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique identifier for the plugin.
	//
	// This is an internal UUID assigned when the plugin is registered.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Group to which the plugin belongs.
	//
	// Groups organize plugins by maintainer or ecosystem.
	//
	// Common groups:
	// - `protocolbuffers` — Official Google protobuf plugins
	// - `grpc` — Official gRPC plugins
	// - `grpc-ecosystem` — gRPC ecosystem plugins (gateway, openapi)
	// - `community` — Community-maintained plugins
	Group string `protobuf:"bytes,2,opt,name=group,proto3" json:"group,omitempty"`
	// Name of the plugin.
	//
	// This is the plugin's identifier within its group.
	//
	// Examples: `go`, `python`, `gateway`, `openapiv2`
	Name string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	// Version of the plugin.
	//
	// Follows semantic versioning (semver) format.
	Version string `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	// Timestamp when the plugin was registered.
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,proto3" json:"created_at,omitempty"`
	// Tags associated with the plugin for categorization.
	//
	// Tags help organize and filter plugins by category.
	// Examples: `go`, `grpc`, `official`, `community`
	Tags          []string `protobuf:"bytes,6,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PluginInfo) Reset() {
	*x = PluginInfo{}
	mi := &file_api_generator_v1_generator_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginInfo) ProtoMessage() {}

func (x *PluginInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_generator_v1_generator_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginInfo.ProtoReflect.Descriptor instead.
func (*PluginInfo) Descriptor() ([]byte, []int) {
	return file_api_generator_v1_generator_proto_rawDescGZIP(), []int{4}
}

func (x *PluginInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PluginInfo) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *PluginInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PluginInfo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *PluginInfo) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *PluginInfo) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

// Request message for creating a plugin.
type CreatePluginRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Group to which the plugin belongs.
	Group string `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
	// Name of the plugin.
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Version of the plugin.
	Version string `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	// Optional plugin configuration.
	Config *structpb.Struct `protobuf:"bytes,4,opt,name=config,proto3" json:"config,omitempty"`
	// Tags for the plugin.
	Tags          []string `protobuf:"bytes,5,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePluginRequest) Reset() {
	*x = CreatePluginRequest{}
	mi := &file_api_generator_v1_generator_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePluginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePluginRequest) ProtoMessage() {}

func (x *CreatePluginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_generator_v1_generator_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePluginRequest.ProtoReflect.Descriptor instead.
func (*CreatePluginRequest) Descriptor() ([]byte, []int) {
	return file_api_generator_v1_generator_proto_rawDescGZIP(), []int{5}
}

func (x *CreatePluginRequest) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *CreatePluginRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreatePluginRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *CreatePluginRequest) GetConfig() *structpb.Struct {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *CreatePluginRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

// Response message for creating a plugin.
type CreatePluginResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The created plugin information.
	Plugin        *PluginInfo `protobuf:"bytes,1,opt,name=plugin,proto3" json:"plugin,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePluginResponse) Reset() {
	*x = CreatePluginResponse{}
	mi := &file_api_generator_v1_generator_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePluginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePluginResponse) ProtoMessage() {}

func (x *CreatePluginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_generator_v1_generator_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePluginResponse.ProtoReflect.Descriptor instead.
func (*CreatePluginResponse) Descriptor() ([]byte, []int) {
	return file_api_generator_v1_generator_proto_rawDescGZIP(), []int{6}
}

func (x *CreatePluginResponse) GetPlugin() *PluginInfo {
	if x != nil {
		return x.Plugin
	}
	return nil
}

// Request message for updating a plugin.
type UpdatePluginRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Group to which the plugin belongs.
	Group string `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
	// Name of the plugin.
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Version of the plugin.
	Version string `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	// New plugin configuration (replaces existing).
	Config *structpb.Struct `protobuf:"bytes,4,opt,name=config,proto3" json:"config,omitempty"`
	// New tags (replaces existing).
	Tags          []string `protobuf:"bytes,5,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePluginRequest) Reset() {
	*x = UpdatePluginRequest{}
	mi := &file_api_generator_v1_generator_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePluginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePluginRequest) ProtoMessage() {}

func (x *UpdatePluginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_generator_v1_generator_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePluginRequest.ProtoReflect.Descriptor instead.
func (*UpdatePluginRequest) Descriptor() ([]byte, []int) {
	return file_api_generator_v1_generator_proto_rawDescGZIP(), []int{7}
}

func (x *UpdatePluginRequest) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *UpdatePluginRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdatePluginRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *UpdatePluginRequest) GetConfig() *structpb.Struct {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *UpdatePluginRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

// Response message for updating a plugin.
type UpdatePluginResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The updated plugin information.
	Plugin        *PluginInfo `protobuf:"bytes,1,opt,name=plugin,proto3" json:"plugin,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePluginResponse) Reset() {
	*x = UpdatePluginResponse{}
	mi := &file_api_generator_v1_generator_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePluginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePluginResponse) ProtoMessage() {}

func (x *UpdatePluginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_generator_v1_generator_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePluginResponse.ProtoReflect.Descriptor instead.
func (*UpdatePluginResponse) Descriptor() ([]byte, []int) {
	return file_api_generator_v1_generator_proto_rawDescGZIP(), []int{8}
}

func (x *UpdatePluginResponse) GetPlugin() *PluginInfo {
	if x != nil {
		return x.Plugin
	}
	return nil
}

// Request message for deleting a plugin.
type DeletePluginRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Group to which the plugin belongs.
	Group string `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
	// Name of the plugin.
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Version of the plugin.
	Version       string `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePluginRequest) Reset() {
	*x = DeletePluginRequest{}
	mi := &file_api_generator_v1_generator_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePluginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePluginRequest) ProtoMessage() {}

func (x *DeletePluginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_generator_v1_generator_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePluginRequest.ProtoReflect.Descriptor instead.
func (*DeletePluginRequest) Descriptor() ([]byte, []int) {
	return file_api_generator_v1_generator_proto_rawDescGZIP(), []int{9}
}

func (x *DeletePluginRequest) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *DeletePluginRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DeletePluginRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

// Response message for deleting a plugin.
type DeletePluginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePluginResponse) Reset() {
	*x = DeletePluginResponse{}
	mi := &file_api_generator_v1_generator_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePluginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePluginResponse) ProtoMessage() {}

func (x *DeletePluginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_generator_v1_generator_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePluginResponse.ProtoReflect.Descriptor instead.
func (*DeletePluginResponse) Descriptor() ([]byte, []int) {
	return file_api_generator_v1_generator_proto_rawDescGZIP(), []int{10}
}

var File_api_generator_v1_generator_proto protoreflect.FileDescriptor

const file_api_generator_v1_generator_proto_rawDesc = "" +
	"\n" +
	" api/generator/v1/generator.proto\x12\x10api.generator.v1\x1a\x1cmcp/options/v1/options.proto\x1a\x10doc/v1/doc.proto\x1a%google/protobuf/compiler/plugin.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x8e\x02\n" +
	"\x13GenerateCodeRequest\x12k\n" +
	"\x16code_generator_request\x18\x01 \x01(\v2..google.protobuf.compiler.CodeGeneratorRequestB\x05\xdaI\x02\b\x01R\x14codeGeneratorRequest\x12\x89\x01\n" +
	"\vplugin_name\x18\x02 \x01(\tBh\xdaIe\b\x01\xa2\x01\x1bprotocolbuffers/go:v1.36.10\x92\x02B^[a-z][a-z0-9-]*/[a-z][a-z0-9-]*:(v[0-9]+\\.[0-9]+\\.[0-9]+|latest)$R\n" +
	"pluginName\"\x86\x01\n" +
	"\x14GenerateCodeResponse\x12n\n" +
	"\x17code_generator_response\x18\x01 \x01(\v2/.google.protobuf.compiler.CodeGeneratorResponseB\x05\xdaI\x02\x10\x01R\x15codeGeneratorResponse\"\x8c\x02\n" +
	"\x0ePluginsRequest\x129\n" +
	"\x05group\x18\x01 \x01(\tB\x1e\xdaI\x1b\xa2\x01\x04grpc\x92\x02\x11^[a-z][a-z0-9-]*$H\x00R\x05group\x88\x01\x01\x125\n" +
	"\x04name\x18\x02 \x01(\tB\x1c\xdaI\x19\xa2\x01\x02go\x92\x02\x11^[a-z][a-z0-9-]*$H\x01R\x04name\x88\x01\x01\x12G\n" +
	"\aversion\x18\x03 \x01(\tB(\xdaI%\xa2\x01\x06v1.5.1\x92\x02\x19^v[0-9]+\\.[0-9]+\\.[0-9]+$H\x02R\aversion\x88\x01\x01\x12 \n" +
	"\x04tags\x18\x04 \x03(\tB\f\xdaI\t\xa2\x01\x06stableR\x04tagsB\b\n" +
	"\x06_groupB\a\n" +
	"\x05_nameB\n" +
	"\n" +
	"\b_version\"m\n" +
	"\x0fPluginsResponse\x12=\n" +
	"\aplugins\x18\x01 \x03(\v2\x1c.api.generator.v1.PluginInfoB\x05\xdaI\x02\x10\x01R\aplugins\x12\x1b\n" +
	"\x05total\x18\x02 \x01(\x05B\x05\xdaI\x02\x10\x01R\x05total\"\xc2\x02\n" +
	"\n" +
	"PluginInfo\x12\x17\n" +
	"\x02id\x18\x01 \x01(\tB\a\xdaI\x04\x10\x01P\x01R\x02id\x12A\n" +
	"\x05group\x18\x02 \x01(\tB+\xdaI(\x10\x01\xa2\x01\x0fprotocolbuffers\x92\x02\x11^[a-z][a-z0-9-]*$R\x05group\x122\n" +
	"\x04name\x18\x03 \x01(\tB\x1e\xdaI\x1b\x10\x01\xa2\x01\x02go\x92\x02\x11^[a-z][a-z0-9-]*$R\x04name\x12F\n" +
	"\aversion\x18\x04 \x01(\tB,\xdaI)\x10\x01\xa2\x01\bv1.36.10\x92\x02\x19^v[0-9]+\\.[0-9]+\\.[0-9]+$R\aversion\x12A\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampB\x05\xdaI\x02\x10\x01R\n" +
	"created_at\x12\x19\n" +
	"\x04tags\x18\x06 \x03(\tB\x05\xdaI\x02\x10\x01R\x04tags\"\x8c\x02\n" +
	"\x13CreatePluginRequest\x126\n" +
	"\x05group\x18\x01 \x01(\tB \xdaI\x1d\b\x01\xa2\x01\x04grpc\x92\x02\x11^[a-z][a-z0-9-]*$R\x05group\x122\n" +
	"\x04name\x18\x02 \x01(\tB\x1e\xdaI\x1b\b\x01\xa2\x01\x02go\x92\x02\x11^[a-z][a-z0-9-]*$R\x04name\x12D\n" +
	"\aversion\x18\x03 \x01(\tB*\xdaI'\b\x01\xa2\x01\x06v1.5.1\x92\x02\x19^v[0-9]+\\.[0-9]+\\.[0-9]+$R\aversion\x12/\n" +
	"\x06config\x18\x04 \x01(\v2\x17.google.protobuf.StructR\x06config\x12\x12\n" +
	"\x04tags\x18\x05 \x03(\tR\x04tags\"S\n" +
	"\x14CreatePluginResponse\x12;\n" +
	"\x06plugin\x18\x01 \x01(\v2\x1c.api.generator.v1.PluginInfoB\x05\xdaI\x02\x10\x01R\x06plugin\"\x8c\x02\n" +
	"\x13UpdatePluginRequest\x126\n" +
	"\x05group\x18\x01 \x01(\tB \xdaI\x1d\b\x01\xa2\x01\x04grpc\x92\x02\x11^[a-z][a-z0-9-]*$R\x05group\x122\n" +
	"\x04name\x18\x02 \x01(\tB\x1e\xdaI\x1b\b\x01\xa2\x01\x02go\x92\x02\x11^[a-z][a-z0-9-]*$R\x04name\x12D\n" +
	"\aversion\x18\x03 \x01(\tB*\xdaI'\b\x01\xa2\x01\x06v1.5.1\x92\x02\x19^v[0-9]+\\.[0-9]+\\.[0-9]+$R\aversion\x12/\n" +
	"\x06config\x18\x04 \x01(\v2\x17.google.protobuf.StructR\x06config\x12\x12\n" +
	"\x04tags\x18\x05 \x03(\tR\x04tags\"S\n" +
	"\x14UpdatePluginResponse\x12;\n" +
	"\x06plugin\x18\x01 \x01(\v2\x1c.api.generator.v1.PluginInfoB\x05\xdaI\x02\x10\x01R\x06plugin\"\xc7\x01\n" +
	"\x13DeletePluginRequest\x126\n" +
	"\x05group\x18\x01 \x01(\tB \xdaI\x1d\b\x01\xa2\x01\x04grpc\x92\x02\x11^[a-z][a-z0-9-]*$R\x05group\x122\n" +
	"\x04name\x18\x02 \x01(\tB\x1e\xdaI\x1b\b\x01\xa2\x01\x02go\x92\x02\x11^[a-z][a-z0-9-]*$R\x04name\x12D\n" +
	"\aversion\x18\x03 \x01(\tB*\xdaI'\b\x01\xa2\x01\x06v1.5.1\x92\x02\x19^v[0-9]+\\.[0-9]+\\.[0-9]+$R\aversion\"\x16\n" +
	"\x14DeletePluginResponse2\xe6\x04\n" +
	"\n" +
	"ServiceAPI\x12e\n" +
	"\fGenerateCode\x12%.api.generator.v1.GenerateCodeRequest\x1a&.api.generator.v1.GenerateCodeResponse\"\x06ҷ,\x02 \x01\x12\xbb\x01\n" +
	"\aPlugins\x12 .api.generator.v1.PluginsRequest\x1a!.api.generator.v1.PluginsResponse\"kҷ,g\n" +
	"\fplugins_list\x12\fList plugins\x1aIList available plugins with optional filters: group, name, version, tags.\x12e\n" +
	"\fCreatePlugin\x12%.api.generator.v1.CreatePluginRequest\x1a&.api.generator.v1.CreatePluginResponse\"\x06ҷ,\x02 \x01\x12e\n" +
	"\fUpdatePlugin\x12%.api.generator.v1.UpdatePluginRequest\x1a&.api.generator.v1.UpdatePluginResponse\"\x06ҷ,\x02 \x01\x12e\n" +
	"\fDeletePlugin\x12%.api.generator.v1.DeletePluginRequest\x1a&.api.generator.v1.DeletePluginResponse\"\x06ҷ,\x02 \x01B:Z8github.com/easyp-tech/service/api/generator/v1;generatorb\x06proto3"

var (
	file_api_generator_v1_generator_proto_rawDescOnce sync.Once
	file_api_generator_v1_generator_proto_rawDescData []byte
)

func file_api_generator_v1_generator_proto_rawDescGZIP() []byte {
	file_api_generator_v1_generator_proto_rawDescOnce.Do(func() {
		file_api_generator_v1_generator_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_generator_v1_generator_proto_rawDesc), len(file_api_generator_v1_generator_proto_rawDesc)))
	})
	return file_api_generator_v1_generator_proto_rawDescData
}

var file_api_generator_v1_generator_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_api_generator_v1_generator_proto_goTypes = []any{
	(*GenerateCodeRequest)(nil),            // 0: api.generator.v1.GenerateCodeRequest
	(*GenerateCodeResponse)(nil),           // 1: api.generator.v1.GenerateCodeResponse
	(*PluginsRequest)(nil),                 // 2: api.generator.v1.PluginsRequest
	(*PluginsResponse)(nil),                // 3: api.generator.v1.PluginsResponse
	(*PluginInfo)(nil),                     // 4: api.generator.v1.PluginInfo
	(*CreatePluginRequest)(nil),            // 5: api.generator.v1.CreatePluginRequest
	(*CreatePluginResponse)(nil),           // 6: api.generator.v1.CreatePluginResponse
	(*UpdatePluginRequest)(nil),            // 7: api.generator.v1.UpdatePluginRequest
	(*UpdatePluginResponse)(nil),           // 8: api.generator.v1.UpdatePluginResponse
	(*DeletePluginRequest)(nil),            // 9: api.generator.v1.DeletePluginRequest
	(*DeletePluginResponse)(nil),           // 10: api.generator.v1.DeletePluginResponse
	(*pluginpb.CodeGeneratorRequest)(nil),  // 11: google.protobuf.compiler.CodeGeneratorRequest
	(*pluginpb.CodeGeneratorResponse)(nil), // 12: google.protobuf.compiler.CodeGeneratorResponse
	(*timestamppb.Timestamp)(nil),          // 13: google.protobuf.Timestamp
	(*structpb.Struct)(nil),                // 14: google.protobuf.Struct
}
var file_api_generator_v1_generator_proto_depIdxs = []int32{
	11, // 0: api.generator.v1.GenerateCodeRequest.code_generator_request:type_name -> google.protobuf.compiler.CodeGeneratorRequest
	12, // 1: api.generator.v1.GenerateCodeResponse.code_generator_response:type_name -> google.protobuf.compiler.CodeGeneratorResponse
	4,  // 2: api.generator.v1.PluginsResponse.plugins:type_name -> api.generator.v1.PluginInfo
	13, // 3: api.generator.v1.PluginInfo.created_at:type_name -> google.protobuf.Timestamp
	14, // 4: api.generator.v1.CreatePluginRequest.config:type_name -> google.protobuf.Struct
	4,  // 5: api.generator.v1.CreatePluginResponse.plugin:type_name -> api.generator.v1.PluginInfo
	14, // 6: api.generator.v1.UpdatePluginRequest.config:type_name -> google.protobuf.Struct
	4,  // 7: api.generator.v1.UpdatePluginResponse.plugin:type_name -> api.generator.v1.PluginInfo
	0,  // 8: api.generator.v1.ServiceAPI.GenerateCode:input_type -> api.generator.v1.GenerateCodeRequest
	2,  // 9: api.generator.v1.ServiceAPI.Plugins:input_type -> api.generator.v1.PluginsRequest
	5,  // 10: api.generator.v1.ServiceAPI.CreatePlugin:input_type -> api.generator.v1.CreatePluginRequest
	7,  // 11: api.generator.v1.ServiceAPI.UpdatePlugin:input_type -> api.generator.v1.UpdatePluginRequest
	9,  // 12: api.generator.v1.ServiceAPI.DeletePlugin:input_type -> api.generator.v1.DeletePluginRequest
	1,  // 13: api.generator.v1.ServiceAPI.GenerateCode:output_type -> api.generator.v1.GenerateCodeResponse
	3,  // 14: api.generator.v1.ServiceAPI.Plugins:output_type -> api.generator.v1.PluginsResponse
	6,  // 15: api.generator.v1.ServiceAPI.CreatePlugin:output_type -> api.generator.v1.CreatePluginResponse
	8,  // 16: api.generator.v1.ServiceAPI.UpdatePlugin:output_type -> api.generator.v1.UpdatePluginResponse
	10, // 17: api.generator.v1.ServiceAPI.DeletePlugin:output_type -> api.generator.v1.DeletePluginResponse
	13, // [13:18] is the sub-list for method output_type
	8,  // [8:13] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_api_generator_v1_generator_proto_init() }
func file_api_generator_v1_generator_proto_init() {
	if File_api_generator_v1_generator_proto != nil {
		return
	}
	file_api_generator_v1_generator_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_generator_v1_generator_proto_rawDesc), len(file_api_generator_v1_generator_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_generator_v1_generator_proto_goTypes,
		DependencyIndexes: file_api_generator_v1_generator_proto_depIdxs,
		MessageInfos:      file_api_generator_v1_generator_proto_msgTypes,
	}.Build()
	File_api_generator_v1_generator_proto = out.File
	file_api_generator_v1_generator_proto_goTypes = nil
	file_api_generator_v1_generator_proto_depIdxs = nil
}
