// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        (unknown)
// source: api/generator/v1/generator.proto

package generator

import (
	_ "github.com/easyp-tech/protoc-gen-easydoc/doc/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	pluginpb "google.golang.org/protobuf/types/pluginpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request message for code generation.
type GenerateCodeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Standard protobuf code generator request.
	//
	// This should contain the proto files to process and any plugin-specific parameters.
	// The request is passed directly to the plugin's stdin.
	CodeGeneratorRequest *pluginpb.CodeGeneratorRequest `protobuf:"bytes,1,opt,name=code_generator_request,json=codeGeneratorRequest,proto3" json:"code_generator_request,omitempty"`
	// Name of the plugin to use for generation.
	//
	// Format: `<group>/<name>:<version>`
	//
	// Examples:
	// - `protocolbuffers/go:v1.36.10`
	// - `grpc/go:v1.5.1`
	// - `grpc-ecosystem/gateway:latest`
	PluginName    string `protobuf:"bytes,2,opt,name=plugin_name,json=pluginName,proto3" json:"plugin_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateCodeRequest) Reset() {
	*x = GenerateCodeRequest{}
	mi := &file_api_generator_v1_generator_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateCodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateCodeRequest) ProtoMessage() {}

func (x *GenerateCodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_generator_v1_generator_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateCodeRequest.ProtoReflect.Descriptor instead.
func (*GenerateCodeRequest) Descriptor() ([]byte, []int) {
	return file_api_generator_v1_generator_proto_rawDescGZIP(), []int{0}
}

func (x *GenerateCodeRequest) GetCodeGeneratorRequest() *pluginpb.CodeGeneratorRequest {
	if x != nil {
		return x.CodeGeneratorRequest
	}
	return nil
}

func (x *GenerateCodeRequest) GetPluginName() string {
	if x != nil {
		return x.PluginName
	}
	return ""
}

// Response message for code generation.
type GenerateCodeResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Standard protobuf code generator response.
	//
	// Contains the generated files and any error messages from the plugin.
	// Check the `error` field in the response for plugin-level errors.
	CodeGeneratorResponse *pluginpb.CodeGeneratorResponse `protobuf:"bytes,1,opt,name=code_generator_response,json=codeGeneratorResponse,proto3" json:"code_generator_response,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *GenerateCodeResponse) Reset() {
	*x = GenerateCodeResponse{}
	mi := &file_api_generator_v1_generator_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateCodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateCodeResponse) ProtoMessage() {}

func (x *GenerateCodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_generator_v1_generator_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateCodeResponse.ProtoReflect.Descriptor instead.
func (*GenerateCodeResponse) Descriptor() ([]byte, []int) {
	return file_api_generator_v1_generator_proto_rawDescGZIP(), []int{1}
}

func (x *GenerateCodeResponse) GetCodeGeneratorResponse() *pluginpb.CodeGeneratorResponse {
	if x != nil {
		return x.CodeGeneratorResponse
	}
	return nil
}

// Request message for listing plugins.
//
// Currently accepts no parameters. Future versions may add filtering options.
type PluginsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PluginsRequest) Reset() {
	*x = PluginsRequest{}
	mi := &file_api_generator_v1_generator_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginsRequest) ProtoMessage() {}

func (x *PluginsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_generator_v1_generator_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginsRequest.ProtoReflect.Descriptor instead.
func (*PluginsRequest) Descriptor() ([]byte, []int) {
	return file_api_generator_v1_generator_proto_rawDescGZIP(), []int{2}
}

// Response message for listing plugins.
type PluginsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// List of available plugins.
	//
	// Plugins are sorted by group, name, and version.
	Plugins       []*PluginInfo `protobuf:"bytes,1,rep,name=plugins,proto3" json:"plugins,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PluginsResponse) Reset() {
	*x = PluginsResponse{}
	mi := &file_api_generator_v1_generator_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginsResponse) ProtoMessage() {}

func (x *PluginsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_generator_v1_generator_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginsResponse.ProtoReflect.Descriptor instead.
func (*PluginsResponse) Descriptor() ([]byte, []int) {
	return file_api_generator_v1_generator_proto_rawDescGZIP(), []int{3}
}

func (x *PluginsResponse) GetPlugins() []*PluginInfo {
	if x != nil {
		return x.Plugins
	}
	return nil
}

// Information about a registered plugin.
type PluginInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique identifier for the plugin.
	//
	// This is an internal UUID assigned when the plugin is registered.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Group to which the plugin belongs.
	//
	// Groups organize plugins by maintainer or ecosystem.
	//
	// Common groups:
	// - `protocolbuffers` — Official Google protobuf plugins
	// - `grpc` — Official gRPC plugins
	// - `grpc-ecosystem` — gRPC ecosystem plugins (gateway, openapi)
	// - `community` — Community-maintained plugins
	Group string `protobuf:"bytes,2,opt,name=group,proto3" json:"group,omitempty"`
	// Name of the plugin.
	//
	// This is the plugin's identifier within its group.
	//
	// Examples: `go`, `python`, `gateway`, `openapiv2`
	Name string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	// Version of the plugin.
	//
	// Follows semantic versioning (semver) format.
	Version string `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	// Timestamp when the plugin was registered.
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PluginInfo) Reset() {
	*x = PluginInfo{}
	mi := &file_api_generator_v1_generator_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginInfo) ProtoMessage() {}

func (x *PluginInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_generator_v1_generator_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginInfo.ProtoReflect.Descriptor instead.
func (*PluginInfo) Descriptor() ([]byte, []int) {
	return file_api_generator_v1_generator_proto_rawDescGZIP(), []int{4}
}

func (x *PluginInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PluginInfo) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *PluginInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PluginInfo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *PluginInfo) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

var File_api_generator_v1_generator_proto protoreflect.FileDescriptor

const file_api_generator_v1_generator_proto_rawDesc = "" +
	"\n" +
	" api/generator/v1/generator.proto\x12\x10api.generator.v1\x1a\x10doc/v1/doc.proto\x1a%google/protobuf/compiler/plugin.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x8e\x02\n" +
	"\x13GenerateCodeRequest\x12k\n" +
	"\x16code_generator_request\x18\x01 \x01(\v2..google.protobuf.compiler.CodeGeneratorRequestB\x05\xdaI\x02\b\x01R\x14codeGeneratorRequest\x12\x89\x01\n" +
	"\vplugin_name\x18\x02 \x01(\tBh\xdaIe\b\x01\xa2\x01\x1bprotocolbuffers/go:v1.36.10\x92\x02B^[a-z][a-z0-9-]*/[a-z][a-z0-9-]*:(v[0-9]+\\.[0-9]+\\.[0-9]+|latest)$R\n" +
	"pluginName\"\x86\x01\n" +
	"\x14GenerateCodeResponse\x12n\n" +
	"\x17code_generator_response\x18\x01 \x01(\v2/.google.protobuf.compiler.CodeGeneratorResponseB\x05\xdaI\x02\x10\x01R\x15codeGeneratorResponse\"\x10\n" +
	"\x0ePluginsRequest\"P\n" +
	"\x0fPluginsResponse\x12=\n" +
	"\aplugins\x18\x01 \x03(\v2\x1c.api.generator.v1.PluginInfoB\x05\xdaI\x02\x10\x01R\aplugins\"\xa6\x02\n" +
	"\n" +
	"PluginInfo\x12\x17\n" +
	"\x02id\x18\x01 \x01(\tB\a\xdaI\x04\x10\x01P\x01R\x02id\x12A\n" +
	"\x05group\x18\x02 \x01(\tB+\xdaI(\x10\x01\xa2\x01\x0fprotocolbuffers\x92\x02\x11^[a-z][a-z0-9-]*$R\x05group\x122\n" +
	"\x04name\x18\x03 \x01(\tB\x1e\xdaI\x1b\x10\x01\xa2\x01\x02go\x92\x02\x11^[a-z][a-z0-9-]*$R\x04name\x12F\n" +
	"\aversion\x18\x04 \x01(\tB,\xdaI)\x10\x01\xa2\x01\bv1.36.10\x92\x02\x19^v[0-9]+\\.[0-9]+\\.[0-9]+$R\aversion\x12@\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampB\x05\xdaI\x02\x10\x01R\tcreatedAt2\xbb\x01\n" +
	"\n" +
	"ServiceAPI\x12]\n" +
	"\fGenerateCode\x12%.api.generator.v1.GenerateCodeRequest\x1a&.api.generator.v1.GenerateCodeResponse\x12N\n" +
	"\aPlugins\x12 .api.generator.v1.PluginsRequest\x1a!.api.generator.v1.PluginsResponseB:Z8github.com/easyp-tech/service/api/generator/v1;generatorb\x06proto3"

var (
	file_api_generator_v1_generator_proto_rawDescOnce sync.Once
	file_api_generator_v1_generator_proto_rawDescData []byte
)

func file_api_generator_v1_generator_proto_rawDescGZIP() []byte {
	file_api_generator_v1_generator_proto_rawDescOnce.Do(func() {
		file_api_generator_v1_generator_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_generator_v1_generator_proto_rawDesc), len(file_api_generator_v1_generator_proto_rawDesc)))
	})
	return file_api_generator_v1_generator_proto_rawDescData
}

var file_api_generator_v1_generator_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_api_generator_v1_generator_proto_goTypes = []any{
	(*GenerateCodeRequest)(nil),            // 0: api.generator.v1.GenerateCodeRequest
	(*GenerateCodeResponse)(nil),           // 1: api.generator.v1.GenerateCodeResponse
	(*PluginsRequest)(nil),                 // 2: api.generator.v1.PluginsRequest
	(*PluginsResponse)(nil),                // 3: api.generator.v1.PluginsResponse
	(*PluginInfo)(nil),                     // 4: api.generator.v1.PluginInfo
	(*pluginpb.CodeGeneratorRequest)(nil),  // 5: google.protobuf.compiler.CodeGeneratorRequest
	(*pluginpb.CodeGeneratorResponse)(nil), // 6: google.protobuf.compiler.CodeGeneratorResponse
	(*timestamppb.Timestamp)(nil),          // 7: google.protobuf.Timestamp
}
var file_api_generator_v1_generator_proto_depIdxs = []int32{
	5, // 0: api.generator.v1.GenerateCodeRequest.code_generator_request:type_name -> google.protobuf.compiler.CodeGeneratorRequest
	6, // 1: api.generator.v1.GenerateCodeResponse.code_generator_response:type_name -> google.protobuf.compiler.CodeGeneratorResponse
	4, // 2: api.generator.v1.PluginsResponse.plugins:type_name -> api.generator.v1.PluginInfo
	7, // 3: api.generator.v1.PluginInfo.created_at:type_name -> google.protobuf.Timestamp
	0, // 4: api.generator.v1.ServiceAPI.GenerateCode:input_type -> api.generator.v1.GenerateCodeRequest
	2, // 5: api.generator.v1.ServiceAPI.Plugins:input_type -> api.generator.v1.PluginsRequest
	1, // 6: api.generator.v1.ServiceAPI.GenerateCode:output_type -> api.generator.v1.GenerateCodeResponse
	3, // 7: api.generator.v1.ServiceAPI.Plugins:output_type -> api.generator.v1.PluginsResponse
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_api_generator_v1_generator_proto_init() }
func file_api_generator_v1_generator_proto_init() {
	if File_api_generator_v1_generator_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_generator_v1_generator_proto_rawDesc), len(file_api_generator_v1_generator_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_generator_v1_generator_proto_goTypes,
		DependencyIndexes: file_api_generator_v1_generator_proto_depIdxs,
		MessageInfos:      file_api_generator_v1_generator_proto_msgTypes,
	}.Build()
	File_api_generator_v1_generator_proto = out.File
	file_api_generator_v1_generator_proto_goTypes = nil
	file_api_generator_v1_generator_proto_depIdxs = nil
}
