// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v0.14.1-v0.16.7-bufbuild-protocompile-easyp-0.20260808053219-77b2379f9a73_modified
// source: api/generator/v1/generator.proto

package generator

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ServiceAPI_GenerateCode_FullMethodName = "/api.generator.v1.ServiceAPI/GenerateCode"
	ServiceAPI_Plugins_FullMethodName      = "/api.generator.v1.ServiceAPI/Plugins"
	ServiceAPI_CreatePlugin_FullMethodName = "/api.generator.v1.ServiceAPI/CreatePlugin"
	ServiceAPI_UpdatePlugin_FullMethodName = "/api.generator.v1.ServiceAPI/UpdatePlugin"
	ServiceAPI_DeletePlugin_FullMethodName = "/api.generator.v1.ServiceAPI/DeletePlugin"
)

// ServiceAPIClient is the client API for ServiceAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// # EasyP Code Generation Service
//
// This service provides a centralized API for executing protobuf/gRPC code generation plugins.
// Plugins run as isolated Docker containers, ensuring version consistency across development teams.
//
// ## Benefits
//
// - **Version Control**: All developers use the same plugin versions
// - **Zero Setup**: No local plugin installation required
// - **Security**: Plugins run in sandboxed containers with resource limits
// - **Auditability**: Centralized logging of all generation requests
//
// ## Quick Start
//
// 1. Call `Plugins` to list available plugins
// 2. Build a `CodeGeneratorRequest` with your proto files
// 3. Call `GenerateCode` with the plugin name and request
// 4. Process the `CodeGeneratorResponse` with generated files
//
// ## Plugin Naming Convention
//
// Plugins are identified using the format: `<group>/<name>:<version>`
//
// Examples:
// - `protocolbuffers/go:v1.36.10` — Official Go protobuf plugin
// - `grpc/go:v1.5.1` — Official gRPC Go plugin
// - `grpc-ecosystem/gateway:v2.27.3` — gRPC-Gateway plugin
//
// Use `latest` as version to get the most recent version:
// - `protocolbuffers/go:latest`
type ServiceAPIClient interface {
	// Generate code using a specified plugin.
	//
	// This method executes a protobuf code generation plugin and returns the generated files.
	// The plugin runs in an isolated Docker container with the following default limits:
	//
	// - **Network**: Disabled (no external access)
	// - **Memory**: 128MB
	// - **CPU**: 1.0 core
	//
	// ## Error Codes
	//
	// | Code | Description |
	// |------|-------------|
	// | `NOT_FOUND` | Plugin not found in registry |
	// | `INVALID_ARGUMENT` | Invalid plugin name format |
	// | `INTERNAL` | Plugin execution failed |
	// | `DEADLINE_EXCEEDED` | Plugin execution timeout |
	GenerateCode(ctx context.Context, in *GenerateCodeRequest, opts ...grpc.CallOption) (*GenerateCodeResponse, error)
	// List available plugins.
	//
	// Returns a list of all plugins registered in the service.
	// Use this to discover available plugins and their versions.
	Plugins(ctx context.Context, in *PluginsRequest, opts ...grpc.CallOption) (*PluginsResponse, error)
	// Create a new plugin registration.
	//
	// Registers a plugin with the given group, name, version, optional config, and tags.
	// Requires an Enterprise license.
	//
	// ## Error Codes
	//
	// | Code | Description |
	// |------|-------------|
	// | `ALREADY_EXISTS` | Plugin with same group/name/version exists |
	// | `INVALID_ARGUMENT` | Invalid plugin name format |
	// | `RESOURCE_EXHAUSTED` | Max plugins limit reached |
	// | `PERMISSION_DENIED` | Enterprise license required |
	CreatePlugin(ctx context.Context, in *CreatePluginRequest, opts ...grpc.CallOption) (*CreatePluginResponse, error)
	// Update an existing plugin.
	//
	// Replaces the config and tags of an existing plugin identified by group/name/version.
	// Requires an Enterprise license.
	//
	// ## Error Codes
	//
	// | Code | Description |
	// |------|-------------|
	// | `NOT_FOUND` | Plugin not found |
	// | `INVALID_ARGUMENT` | Invalid plugin name format |
	// | `PERMISSION_DENIED` | Enterprise license required |
	UpdatePlugin(ctx context.Context, in *UpdatePluginRequest, opts ...grpc.CallOption) (*UpdatePluginResponse, error)
	// Delete a plugin.
	//
	// Removes a plugin from the registry by group/name/version.
	// Requires an Enterprise license.
	//
	// ## Error Codes
	//
	// | Code | Description |
	// |------|-------------|
	// | `NOT_FOUND` | Plugin not found |
	// | `PERMISSION_DENIED` | Enterprise license required |
	DeletePlugin(ctx context.Context, in *DeletePluginRequest, opts ...grpc.CallOption) (*DeletePluginResponse, error)
}

type serviceAPIClient struct {
	cc grpc.ClientConnInterface
}

func NewServiceAPIClient(cc grpc.ClientConnInterface) ServiceAPIClient {
	return &serviceAPIClient{cc}
}

func (c *serviceAPIClient) GenerateCode(ctx context.Context, in *GenerateCodeRequest, opts ...grpc.CallOption) (*GenerateCodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenerateCodeResponse)
	err := c.cc.Invoke(ctx, ServiceAPI_GenerateCode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceAPIClient) Plugins(ctx context.Context, in *PluginsRequest, opts ...grpc.CallOption) (*PluginsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PluginsResponse)
	err := c.cc.Invoke(ctx, ServiceAPI_Plugins_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceAPIClient) CreatePlugin(ctx context.Context, in *CreatePluginRequest, opts ...grpc.CallOption) (*CreatePluginResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreatePluginResponse)
	err := c.cc.Invoke(ctx, ServiceAPI_CreatePlugin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceAPIClient) UpdatePlugin(ctx context.Context, in *UpdatePluginRequest, opts ...grpc.CallOption) (*UpdatePluginResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdatePluginResponse)
	err := c.cc.Invoke(ctx, ServiceAPI_UpdatePlugin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceAPIClient) DeletePlugin(ctx context.Context, in *DeletePluginRequest, opts ...grpc.CallOption) (*DeletePluginResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeletePluginResponse)
	err := c.cc.Invoke(ctx, ServiceAPI_DeletePlugin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ServiceAPIServer is the server API for ServiceAPI service.
// All implementations should embed UnimplementedServiceAPIServer
// for forward compatibility.
//
// # EasyP Code Generation Service
//
// This service provides a centralized API for executing protobuf/gRPC code generation plugins.
// Plugins run as isolated Docker containers, ensuring version consistency across development teams.
//
// ## Benefits
//
// - **Version Control**: All developers use the same plugin versions
// - **Zero Setup**: No local plugin installation required
// - **Security**: Plugins run in sandboxed containers with resource limits
// - **Auditability**: Centralized logging of all generation requests
//
// ## Quick Start
//
// 1. Call `Plugins` to list available plugins
// 2. Build a `CodeGeneratorRequest` with your proto files
// 3. Call `GenerateCode` with the plugin name and request
// 4. Process the `CodeGeneratorResponse` with generated files
//
// ## Plugin Naming Convention
//
// Plugins are identified using the format: `<group>/<name>:<version>`
//
// Examples:
// - `protocolbuffers/go:v1.36.10` — Official Go protobuf plugin
// - `grpc/go:v1.5.1` — Official gRPC Go plugin
// - `grpc-ecosystem/gateway:v2.27.3` — gRPC-Gateway plugin
//
// Use `latest` as version to get the most recent version:
// - `protocolbuffers/go:latest`
type ServiceAPIServer interface {
	// Generate code using a specified plugin.
	//
	// This method executes a protobuf code generation plugin and returns the generated files.
	// The plugin runs in an isolated Docker container with the following default limits:
	//
	// - **Network**: Disabled (no external access)
	// - **Memory**: 128MB
	// - **CPU**: 1.0 core
	//
	// ## Error Codes
	//
	// | Code | Description |
	// |------|-------------|
	// | `NOT_FOUND` | Plugin not found in registry |
	// | `INVALID_ARGUMENT` | Invalid plugin name format |
	// | `INTERNAL` | Plugin execution failed |
	// | `DEADLINE_EXCEEDED` | Plugin execution timeout |
	GenerateCode(context.Context, *GenerateCodeRequest) (*GenerateCodeResponse, error)
	// List available plugins.
	//
	// Returns a list of all plugins registered in the service.
	// Use this to discover available plugins and their versions.
	Plugins(context.Context, *PluginsRequest) (*PluginsResponse, error)
	// Create a new plugin registration.
	//
	// Registers a plugin with the given group, name, version, optional config, and tags.
	// Requires an Enterprise license.
	//
	// ## Error Codes
	//
	// | Code | Description |
	// |------|-------------|
	// | `ALREADY_EXISTS` | Plugin with same group/name/version exists |
	// | `INVALID_ARGUMENT` | Invalid plugin name format |
	// | `RESOURCE_EXHAUSTED` | Max plugins limit reached |
	// | `PERMISSION_DENIED` | Enterprise license required |
	CreatePlugin(context.Context, *CreatePluginRequest) (*CreatePluginResponse, error)
	// Update an existing plugin.
	//
	// Replaces the config and tags of an existing plugin identified by group/name/version.
	// Requires an Enterprise license.
	//
	// ## Error Codes
	//
	// | Code | Description |
	// |------|-------------|
	// | `NOT_FOUND` | Plugin not found |
	// | `INVALID_ARGUMENT` | Invalid plugin name format |
	// | `PERMISSION_DENIED` | Enterprise license required |
	UpdatePlugin(context.Context, *UpdatePluginRequest) (*UpdatePluginResponse, error)
	// Delete a plugin.
	//
	// Removes a plugin from the registry by group/name/version.
	// Requires an Enterprise license.
	//
	// ## Error Codes
	//
	// | Code | Description |
	// |------|-------------|
	// | `NOT_FOUND` | Plugin not found |
	// | `PERMISSION_DENIED` | Enterprise license required |
	DeletePlugin(context.Context, *DeletePluginRequest) (*DeletePluginResponse, error)
}

// UnimplementedServiceAPIServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedServiceAPIServer struct{}

func (UnimplementedServiceAPIServer) GenerateCode(context.Context, *GenerateCodeRequest) (*GenerateCodeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GenerateCode not implemented")
}
func (UnimplementedServiceAPIServer) Plugins(context.Context, *PluginsRequest) (*PluginsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Plugins not implemented")
}
func (UnimplementedServiceAPIServer) CreatePlugin(context.Context, *CreatePluginRequest) (*CreatePluginResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreatePlugin not implemented")
}
func (UnimplementedServiceAPIServer) UpdatePlugin(context.Context, *UpdatePluginRequest) (*UpdatePluginResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdatePlugin not implemented")
}
func (UnimplementedServiceAPIServer) DeletePlugin(context.Context, *DeletePluginRequest) (*DeletePluginResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeletePlugin not implemented")
}
func (UnimplementedServiceAPIServer) testEmbeddedByValue() {}

// UnsafeServiceAPIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ServiceAPIServer will
// result in compilation errors.
type UnsafeServiceAPIServer interface {
	mustEmbedUnimplementedServiceAPIServer()
}

func RegisterServiceAPIServer(s grpc.ServiceRegistrar, srv ServiceAPIServer) {
	// If the following call panics, it indicates UnimplementedServiceAPIServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ServiceAPI_ServiceDesc, srv)
}

func _ServiceAPI_GenerateCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateCodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceAPIServer).GenerateCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ServiceAPI_GenerateCode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceAPIServer).GenerateCode(ctx, req.(*GenerateCodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServiceAPI_Plugins_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PluginsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceAPIServer).Plugins(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ServiceAPI_Plugins_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceAPIServer).Plugins(ctx, req.(*PluginsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServiceAPI_CreatePlugin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePluginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceAPIServer).CreatePlugin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ServiceAPI_CreatePlugin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceAPIServer).CreatePlugin(ctx, req.(*CreatePluginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServiceAPI_UpdatePlugin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePluginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceAPIServer).UpdatePlugin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ServiceAPI_UpdatePlugin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceAPIServer).UpdatePlugin(ctx, req.(*UpdatePluginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServiceAPI_DeletePlugin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeletePluginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceAPIServer).DeletePlugin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ServiceAPI_DeletePlugin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceAPIServer).DeletePlugin(ctx, req.(*DeletePluginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ServiceAPI_ServiceDesc is the grpc.ServiceDesc for ServiceAPI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ServiceAPI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.generator.v1.ServiceAPI",
	HandlerType: (*ServiceAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GenerateCode",
			Handler:    _ServiceAPI_GenerateCode_Handler,
		},
		{
			MethodName: "Plugins",
			Handler:    _ServiceAPI_Plugins_Handler,
		},
		{
			MethodName: "CreatePlugin",
			Handler:    _ServiceAPI_CreatePlugin_Handler,
		},
		{
			MethodName: "UpdatePlugin",
			Handler:    _ServiceAPI_UpdatePlugin_Handler,
		},
		{
			MethodName: "DeletePlugin",
			Handler:    _ServiceAPI_DeletePlugin_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/generator/v1/generator.proto",
}
