auth_enabled: false

server:
  http_listen_port: 3100

common:
  ring:
    instance_addr: 127.0.0.1
    kvstore:
      store: inmemory
  replication_factor: 1
  path_prefix: /tmp/loki

schema_config:
  configs:
    - from: 2020-05-15
      store: tsdb
      object_store: s3
      schema: v13
      index:
        prefix: index_
        period: 24h

storage_config:
  aws:
    endpoint: rustfs:9000
    access_key_id: rustfsadmin
    secret_access_key: rustfsadmin
    s3forcepathstyle: true
    insecure: true
    bucketnames: loki-chunks

  tsdb_shipper:
    active_index_directory: /tmp/loki/tsdb-index
    cache_location: /tmp/loki/tsdb-cache

limits_config:
  allow_structured_metadata: false

ruler:
  storage:
    type: s3
    s3:
      endpoint: rustfs:9000
      access_key_id: rustfsadmin
      secret_access_key: rustfsadmin
      s3forcepathstyle: true
      insecure: true
      bucketnames: loki-ruler
